name: Execute rooftop challenge

on:
  push:
    branches:
      - "master"

env:
  EMAIL: ${{ secrets.EMAIL }}
  ROOT_URL: ${{ secrets.ROOT_URL }}

jobs:
  challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Execute Tests
        run: |
          EMAIL=${{ env.EMAIL }} ROOT_URL=${{ env.ROOT_URL }} python3 -m unittest 

      - name: Run Challenge
        run: |
          ./main.py